services:
  mongodb:
    image: 'mongo:8.0'
    container_name: 'mongodbUrlShotener'
    ports:
      - '27017'
    environment:
      - 'MONGO_INITDB_DATABASE=${database}'
      - 'MONGO_INITDB_ROOT_PASSWORD=${password}'
      - 'MONGO_INITDB_ROOT_USERNAME=${username}'